name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /mnt/d/Docker/namgun-portal
          git fetch origin main
          git reset --hard origin/main

      - name: Build and deploy
        run: |
          cd /mnt/d/Docker/namgun-portal
          docker compose --profile prod up -d --build

      - name: Health check
        run: |
          echo "Waiting for services to start..."
          sleep 15
          curl -sf http://localhost:8080/api/health || exit 1
          echo "Deploy successful"
